[build]
  base = "."
  command = "npm install -g mystmd && myst build --html"
  publish = "_build/html"

[[redirects]]
  from = "/*"
  to = "https://eds-book.netlify.app/95199651-9e81-4cae-a3a7-66398a9a5f62/:splat"
  status = 200
  force = false
